### ISSUE TITLE
On macOS Mojave, the sample app reports Vertex Shader: ERROR: 0:1: '' :  version '330' is not supported.

### ISSUE THREAD

**Issue by gkopff** [MoncefYabi/Koge#4]
On macOS Mojave, the sample app reports the following to stdout:

Vertex Shader: ERROR: 0:1: '' :  version '330' is not supported.
ERROR: 0:1: '' : syntax error: #version

A window is created (and the background music plays), but the background is painted entirely red.

![image](https://user-images.githubusercontent.com/685726/83737884-f42b3900-a696-11ea-9a47-645249bf62cf.png)

**Comment by gkopff** [comment]
I can confirm the same message when running on macOS Catalina.  The only difference there was the window was painted black, not red.

**Comment by MoncefYabi** [comment]
It seems that the Vertex Shader in version 330 is not supported in your environment. 
I downgraded the Shader version to 150, in the Koge master branch. The [app.kt](https://github.com/KogeLabs/Koge/blob/master/src/test/kotlin/org/koge/test/app.kt ) is located in koge-master under the test package. 
Please clone and test the new Koge-master repo and tell me, whether this works.

**Comment by gkopff** [comment]
Similar issue I'm afraid:

````
Vertex Shader: ERROR: 0:1: '' :  version '150' is not supported
ERROR: 0:1: '' : syntax error: #version
````

**Comment by MoncefYabi** [comment]
Hi @gkopff, I think, I was able to find the issue. The bellow OpenGL hints are set during the creation of a game session. They are mandatory for Mac Os X for GL 3.2+ context creation.
```
glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3)
glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3)
glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE)
glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE)
```
This hints are missing and I have added them to the main game initialization method https://github.com/KogeLabs/Koge/commit/2bcacaa5b22f9b83998641dd6ce108a14e53e7c6.  

I do not have a Mac and I couldn't manage to test again on my buddy's Mac. 
Please let me know if the new commit did the trick for you?

**Comment by gkopff** [comment]
@MoncefYabi some progress 👍  ... but not yet working.

The shader errors are no longer printed.  Standard out prints this now:

```
Program Validation: Validation Failed: No vertex array object bound.
```

The window appears, but it painted entirely red.

**Comment by MoncefYabi** [comment]
I switched the [attribute location for OpenGL from automatic to explicit binding](https://stackoverflow.com/questions/4635913/explicit-vs-automatic-attribute-location-binding-for-opengl-shaders). I hope it will do the trick!

**Comment by gkopff** [comment]
I'm running `152e91a` and unfortunately I still get:

```
Program Validation: Validation Failed: No vertex array object bound.
```

**Comment by MoncefYabi** [comment]
@gkopff, many thanks for testing,
I did just commit an other fix, the ```Validation Failed: No vertex array object bound``` error should be fixed now. 
Please redo an other test, but this time enable the OpenGL/LWJGL debug mode by passing the argument '-Dorg.lwjgl.util.Debug=true' to the JVM as explained here: https://github.com/LWJGL/lwjgl3-wiki/wiki/2.5.-Troubleshooting
